#!/usr/bin/env bash

build_image () {

    docker buildx build --file docker/Dockerfile --progress=plain --tag data:latest .
}

stop_container () {

    container_id=`sudo docker ps -aqf "name=data"`
    docker container stop $container_id
}

start_container () {
    docker run --name=data -d data:latest tail -f /dev/null 
}

copy_requirements_txt_from_container () {

    container_id=`sudo docker ps -aqf "name=data"`
    docker cp $container_id:/var/www/data/requirements.txt .
}

build_image
start_container
sleep 1
copy_requirements_txt_from_container
stop_container