#!/usr/bin/env bash

token="datax"

build_image () {

    docker buildx build --file docker/Dockerfile --progress=plain --tag "$token:latest" .
}

stop_container () {

    docker container stop $token
    sleep 1
    docker container rm $token 
}

start_container () {
    docker run --name=$token -d "$token:latest" tail -f /dev/null 
}

copy_requirements_txt_from_container () {

    container_id=`sudo docker ps -aqf "name=$token"`
    docker cp $container_id:/var/www/datax/requirements.txt .
}

build_image
stop_container
start_container
sleep 1
copy_requirements_txt_from_container
stop_container